<a href="https://colab.research.google.com/github/alvinadar/Certificate_gen_2026/blob/main/20_Certificate_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cert Generator

### Goal of this project is to:

1. `Do simple Data Analysis`
    - Deal with missing values
    - Format the date or text

2. `Enchance Python Concepts`
3. `Explore more 3rd party libraries - reportlab`

---

---
##1. Download & Importing packages for this project
---

In [25]:
# install external package "reportlab" because it is not in normal python
# "reportlab" is a library to link pdf to python program

# "pip" is a python package downloader (package manager)
#  pip package manager is like ur Appstore to download apps


!pip install reportlab

Requirement already satisfied: reportlab in /usr/local/lib/python3.13/dist-packages (5.0.1)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.13/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.13/dist-packages (from reportlab) (3.4.9)

In [26]:
import numpy as np
import pandas as pd

from reportlab.lib.pagesizes import landscape, A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

---
## 2. Reading and Exploring the Excel File
---

In [27]:
df = pd.read_excel("/content/drive/MyDrive/Certificate Generator/dataset.xlsx")

df.head()

                 Name           Course   CourseLevel       Date
0  Christy Cunningham           Python      Beginner 2023-09-10
1      Douglas Tucker           PYTHON       MASTER  2023-09-11
2      Travis Walters             Java  Intermediate 2023-09-12
3    Nathaniel Harris  Web Development      Advanced 2023-09-13
4                   -              NaN      Advanced        NaT

In [28]:
# realise that 2 of the rows are empty (half-empty will NaN, - , NaT)

# NaT - Not a Time
# NaN - Not a Number

# basically empty values (null values)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         13 non-null     object
 1   Course       11 non-null     object
 2   CourseLevel  12 non-null     object
 3   Date         11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 548.0+ bytes

---
## 3. Data Cleaning (Data analysis)

`Data cleaning` - Formatting the data before doing the certificate generator logic

- Deal with missing values
- Format the date or text

---

In [30]:
# the 3 problems with the original dataset (raw excel file)

# 1. Inconsistency formatting in "Course" & "CourseLevel" columns - (some are capitalized but some are uppercase)
# 2. Date format (yyyy/mm/dd) --> we want to change into (xq/mm/yyyy)
# 3. Empty rows (half empty row 4 & 8)

# we are going to solve these problems using Data analysis with Pandas!

In [31]:
df = df.dropna()# drop all the rows that have AT LEAST 1 empty column

# in this case it will drop row 4 & row 8

In [32]:
df

                  Name                 Course   CourseLevel       Date
0   Christy Cunningham                 Python      Beginner 2023-09-10
1       Douglas Tucker                 PYTHON       MASTER  2023-09-11
2       Travis Walters                   Java  Intermediate 2023-09-12
3     Nathaniel Harris        Web Development      Advanced 2023-09-13
5         Tonya Carter  AI & Machine Learning      Beginner 2023-09-14
6           Erik Smith     Mobile Development      Beginner 2023-09-15
7   Kristopher Johnson                 Python      Beginner 2023-09-16
9          Robert Buck                 PYTHON       Master  2023-09-17
10     Joseph Mcdonald                   Java  Intermediate 2023-09-18
11       Jerome Abbott        Web Development      Advanced 2023-09-19
12       William Riley  AI & Machine Learning      Beginner 2023-09-20

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 12
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         11 non-null     object
 1   Course       11 non-null     object
 2   CourseLevel  11 non-null     object
 3   Date         11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 440.0+ bytes

In [34]:
# Problem 2:  Date format (yyyy/mm/dd) --> we want to change into (dd/mm/yyyy)

df['Date']

# this gives us the "Date" column in pandas Series
# Date format (yyyy/mm/dd) --> we want to change into (dd/mm/yyyy)

0    2023-09-10
1    2023-09-11
2    2023-09-12
3    2023-09-13
5    2023-09-14
6    2023-09-15
7    2023-09-16
9    2023-09-17
10   2023-09-18
11   2023-09-19
12   2023-09-20
Name: Date, dtype: datetime64[ns]

In [35]:
# let's look at the first row of "Date"

# iloc --> index location

df['Date'].iloc[0]

# .iloc[0] --> index location of 0 (the first row)
# Timestamp is a data type to represent time in (excel, df)
# For example, we need to change  Timestamp('2023-09-10 00:00:00') --> "10/09/2023"

Timestamp('2023-09-10 00:00:00')

In [36]:
df['FormattedDate'] = df['Date'].dt.strftime("%d/%m/%Y")

# in order to format dates, u can access "dt" in Pandas
# dt --> datetime (u will access to a lot of commands on dealing with dates inside the column)
# one of the commands in "dt" is --> strftime
# strftime (string formatted time) --> convert timestamp object into string representations (following a specified format)
df

,Name,Course,CourseLevel,Date,FormattedDate
0,Christy Cunningham,Python,Beginner,2023-09-10,10/09/2023
1,Douglas Tucker,PYTHON,MASTER,2023-09-11,11/09/2023
2,Travis Walters,Java,Intermediate,2023-09-12,12/09/2023
3,Nathaniel Harris,Web Development,Advanced,2023-09-13,13/09/2023
5,Tonya Carter,AI & Machine Learning,Beginner,2023-09-14,14/09/2023
6,Erik Smith,Mobile Development,Beginner,2023-09-15,15/09/2023
7,Kristopher Johnson,Python,Beginner,2023-09-16,16/09/2023
9,Robert Buck,PYTHON,Master,2023-09-17,17/09/2023
10,Joseph Mcdonald,Java,Intermediate,2023-09-18,18/09/2023
11,Jerome Abbott,Web Development,Advanced,2023-09-19,19/09/2023
12,William Riley,AI & Machine Learning,Beginner,2023-09-20,20/09/2023

In [37]:
#Y --> 2023
#y --> 23

In [38]:
df['FormattedDate'].dtype

# O --> Object --> string

dtype('O')

In [39]:
# remove the "Date" column (because it is useless to us)

df = df.drop("Date",axis = 1)

In [40]:
df.head()

                 Name                 Course   CourseLevel FormattedDate
0  Christy Cunningham                 Python      Beginner    10/09/2023
1      Douglas Tucker                 PYTHON       MASTER     11/09/2023
2      Travis Walters                   Java  Intermediate    12/09/2023
3    Nathaniel Harris        Web Development      Advanced    13/09/2023
5        Tonya Carter  AI & Machine Learning      Beginner    14/09/2023

In [41]:
# Problem 1: Inconsistency formatting in "Course" & "CourseLevel" columns - (some are capitalized but some are uppercase)

# in order to format string, u can access "str" in Pandas

df['Course'] = df['Course'].str.capitalize()

df

                  Name                 Course   CourseLevel FormattedDate
0   Christy Cunningham                 Python      Beginner    10/09/2023
1       Douglas Tucker                 Python       MASTER     11/09/2023
2       Travis Walters                   Java  Intermediate    12/09/2023
3     Nathaniel Harris        Web development      Advanced    13/09/2023
5         Tonya Carter  Ai & machine learning      Beginner    14/09/2023
6           Erik Smith     Mobile development      Beginner    15/09/2023
7   Kristopher Johnson                 Python      Beginner    16/09/2023
9          Robert Buck                 Python       Master     17/09/2023
10     Joseph Mcdonald                   Java  Intermediate    18/09/2023
11       Jerome Abbott        Web development      Advanced    19/09/2023
12       William Riley  Ai & machine learning      Beginner    20/09/2023

In [42]:
df['CourseLevel'] = df["CourseLevel"].str.capitalize()

In [43]:
df.head()

                 Name                 Course   CourseLevel FormattedDate
0  Christy Cunningham                 Python      Beginner    10/09/2023
1      Douglas Tucker                 Python       Master     11/09/2023
2      Travis Walters                   Java  Intermediate    12/09/2023
3    Nathaniel Harris        Web development      Advanced    13/09/2023
5        Tonya Carter  Ai & machine learning      Beginner    14/09/2023

# 4. Registering Fonts into our Project

In [44]:
# Defining the path to the fonts folder (it is like storing a string inside 'fonts_path' variable)

fonts_path = "/content/drive/MyDrive/Certificate Generator/fonts"

In [45]:
 # registering 2 fonts into this project

 # pdfmetrics is 1 of the packages we imported! (this package is used to register fonts so that we can use it with pdf files)

# .ttf is an entension for fonts file

# one of the commands in pdfmetrics is --> registerFont()

# TTFont() is another package we imported!

# TTFont() will need 2 inputs
# 1st input --> what font are u registering?
# 2nd input --> where is the file of the font (concat the "fonts folder" with the file )

pdfmetrics.registerFont(TTFont('Lora-Bold', fonts_path + "/Lora-Bold.ttf" ))
pdfmetrics.registerFont(TTFont('Lora-Regular', fonts_path + "/Lora-Regular.ttf" ))

## 5. Creating Certificate Logic Function

In [67]:
# this function will receive 4 inputs (name,courseName,courseLevel,date)

# we are going to REUSE THIS FUNCTION 11 times (since there are 11 students) - using a for loop to loop through the dataset
# for each student, this function will receive their name, course, level & date (4 inputs)

def certificate_generator(name,courseName,courseLevel,date):

  # store the generated file name inside a variable "pdf_file_name"
  pdf_file_name = "/content/drive/MyDrive/Certificate Generator/certificates/" + name + "-" + courseName + "-" + courseLevel + ".pdf"

  #canvas = blank screen (A4 landscape size)
  # we are storing this canvas inside this .pdf (file path --> "pdf_file_name")

  # creating a canvas object from reportLab import and inserting our certificate template FOLDER path into it
  # pagesize = landscape(A4) --> making it an A4 paper landscape canvas

  # storing it inside a variable called 'c'
  # basically we have a blank landscape A4 virtual paper in our .pdf file

  # Canvas() will need 2 inputs
  # 1st input - where are you storing it?  and the file name
  # 2nd input - what size?
  c = canvas.Canvas(pdf_file_name,pagesize=landscape(A4))

  template = "/content/drive/MyDrive/Certificate Generator/certificate_template.jpg"

  center_x = c._pagesize[0]/2#Get the width of the canvas

  center_y = c._pagesize[1]/2#Get the height of the canvas

  #.drawImage() requires 5 inputs
  # 1st input --> image --> what are u drawing on the empty canvas?? --> certifcate template
  # 4th & 5th input --> width & height --> how big you want the image (certificate tempalte to be?) --> normal A4 size
  c.drawImage(template,0,0,A4[1],A4[0])

  # now that we got the centre of x & y....
  # Let's now set font and draw text

   #--------------
  # .setFont() --> needs 2 inputs
  # 1st input --> font type
  # 2nd input --> font size (in px)

  #--------------
  # .drawCentredString() --> needs 3 inputs
  # 1st input --> x axis on the canvas to draw
  # 2nd input --> y axis on the canvas to draw
  # 3rd input --> what u are drawing on the canvas


  #1.Name
  c.setFont('Lora-Bold',30)
  c.drawCentredString(center_x,center_y-46,name)

  # 2. CourseName & CourseLevel
  c.setFont('Lora-Bold',28)
  c.drawCentredString(center_x, center_y - 105, courseName + " - " + courseLevel)

  #Date
  c.setFont('Lora-Bold',17)
  c.drawCentredString(center_x+190,center_y-160,date)

  #Uniqe ID Cert ID (Check cell below before coding this)
  cert_id = "Cert ID: " + str(pd.Timestamp.now().timestamp()).replace(".","")
  c.setFont('Lora-Regular',12)
  c.drawCentredString(center_x + 266, center_y - 230,cert_id.upper())

  c.save()#Save the canvas

In [68]:
# certificate_generator function needs 4 inputs --> (name,courseName,courseLevel,date)

certificate_generator("Alvin","Python","Begineer","20/06/2024")

In [64]:
# For CERT ID, it has to be unique, we can uniquely generate an ID based on current time (using pd.Timestamp)
print(pd.Timestamp.now())
print(pd.Timestamp.now().timestamp())# Unix timestamp (number of seconds since January 1 1970)
print(str(pd.Timestamp.now().timestamp()).replace(".",""))

2026-09-19 10:12:26.936238
1789812746.936752
1789812746936909

In [71]:
# there are 11 students, the idea is USING THE FUNCTION 11 TIMES (with different 4 inputs --> (name,courseName,courseLevel,date))


# use a for loop --> loop 11 times --> use function 11 times based on different 4 inputs

#Generate certificates for each row in the DataFrame (11rows)
#execute this function 11 times --> generate 11 certs


#remember you can loop through an array with a for loop
for x in ["Jun","The","Duck"]:
  print(x)

Jun
The
Duck

In [72]:
df

                  Name                 Course   CourseLevel FormattedDate
0   Christy Cunningham                 Python      Beginner    10/09/2023
1       Douglas Tucker                 Python       Master     11/09/2023
2       Travis Walters                   Java  Intermediate    12/09/2023
3     Nathaniel Harris        Web development      Advanced    13/09/2023
5         Tonya Carter  Ai & machine learning      Beginner    14/09/2023
6           Erik Smith     Mobile development      Beginner    15/09/2023
7   Kristopher Johnson                 Python      Beginner    16/09/2023
9          Robert Buck                 Python       Master     17/09/2023
10     Joseph Mcdonald                   Java  Intermediate    18/09/2023
11       Jerome Abbott        Web development      Advanced    19/09/2023
12       William Riley  Ai & machine learning      Beginner    20/09/2023

In [73]:
# again we need to loop through the df

for x in df:
  print(x)

Name
Course
CourseLevel
FormattedDate

In [75]:
# df.iterrows gives u a
# df.iterrows gives you 2 items (index, item(row))

for index,x in df.iterrows():
  print(index)

0
1
2
3
5
6
7
9
10
11
12

In [77]:
for index,x in df.iterrows():
  print(x)
  print('---------------------------------------')

Name             Christy Cunningham
Course                       Python
CourseLevel                Beginner
FormattedDate            10/09/2023
Name: 0, dtype: object
---------------------------------------
Name             Douglas Tucker
Course                   Python
CourseLevel             Master
FormattedDate        11/09/2023
Name: 1, dtype: object
---------------------------------------
Name             Travis Walters
Course                     Java
CourseLevel        Intermediate
FormattedDate        12/09/2023
Name: 2, dtype: object
---------------------------------------
Name             Nathaniel Harris
Course            Web development
CourseLevel              Advanced
FormattedDate          13/09/2023
Name: 3, dtype: object
---------------------------------------
Name                      Tonya Carter
Course           Ai & machine learning
CourseLevel                   Beginner
FormattedDate               14/09/2023
Name: 5, dtype: object
---------------------------------------
Name                     Erik Smith
Course           Mobile development
CourseLevel                Beginner
FormattedDate            15/09/2023
Name: 6, dtype: object
---------------------------------------
Name             Kristopher Johnson
Course                       Python
CourseLevel                Beginner
FormattedDate            16/09/2023
Name: 7, dtype: object
---------------------------------------
Name             Robert Buck
Course                Python
CourseLevel          Master
FormattedDate     17/09/2023
Name: 9, dtype: object
---------------------------------------
Name             Joseph Mcdonald
Course                      Java
CourseLevel         Intermediate
FormattedDate         18/09/2023
Name: 10, dtype: object
---------------------------------------
Name               Jerome Abbott
Course           Web development
CourseLevel             Advanced
FormattedDate         19/09/2023
Name: 11, dtype: object
---------------------------------------
Name                     William Riley
Course           Ai & machine learning
CourseLevel                   Beginner
FormattedDate               20/09/2023
Name: 12, dtype: object
---------------------------------------

In [78]:
for index,x in df.iterrows():
  certificate_generator(x['Name'],x['Course'],x['CourseLevel'],x['FormattedDate'])

print(str(len(df)) + "certificate generated succesfully.")

11certificate generated succesfully.